### ISSUE TITLE
tt-topo runs with no arguments using the default values without confirmation

### ISSUE THREAD

**Issue by hmohiuddinTT** [tenstorrent/tt-topology#2]
I ran `tt-topology` with no arguments and it used the default arguments to flash my system when it was not what I wanted to flash.

![image](https://github.com/tenstorrent/tt-topology/assets/124714595/5b84cb10-2fe9-4228-a217-1b1f3f3ac398)

I think by default we should either ask the user for confirmation before flashing or remove the defaults. For automation we can add a --force that doesn't require a confirmation.

**Comment by sbansalTT** [comment]
Fixed as of v1.1.2
